var blogData = [
    {"key":"BLOG01", "name":"Core Interview Question and Answer", "about":"InterView Question needed all candidate. Every candidate has need clear concept there Subject waish Question", "img":"https://i.ibb.co/86NK0Sb/10-vritual-DOM.jpg", "url":"https://medium.com/@ariful4966/core-interview-question-and-answer-e3492a292427", "website":"medium.com"},
    {"key":"BLOG02", "name":"Some FAQ about React.", "about":"SyntheticEvent is a cross-browser wrapper around the browser’s native event.","img":"https://i.ibb.co/qBHRHnk/Component-Lifecycle.png", "url":"https://medium.com/@ariful4966/some-faq-about-react-176a7c09d7fc", "website":"medium.com"},
    {"key":"BLOG03", "name":"10 concept of React library", "img":"https://i.ibb.co/Jj5pwjH/props.png","about":"useCallback is one of the additional Hooks of React. useMemo is similar to this.", "url":"https://medium.com/@ariful4966/10-concept-of-react-library-29680556f39a", "website":"medium.com"},
    {"key":"BLOG04", "name":"Some Most Important JavaScript Interview Question","about":"DOM stands for Document Object Model is an interface (API) for HTML and XML documents.", "img":"https://i.ibb.co/R2SxYTM/js-IQ.jpg", "url":"https://medium.com/@ariful4966/some-most-important-javascript-interview-question-34f55540fb0c", "website":"medium.com"},
    {"key":"BLOG05", "name":"Simple knowledge about react.js","about":"Like the actual DOM, the virtual DOM is a node tree that lists elements and their attributes and content as objects and properties.", "img":"https://i.ibb.co/Q8YgFPM/vs-dom.png", "url":"https://medium.com/@ariful4966/simple-knowledge-about-react-js-67b47896a09", "website":"medium.com"},
    {"key":"BLOG06", "name":"Ten things help for developer","about":"The eval() function will execute a string of JavaScript code in the local scope", "img":"https://i.ibb.co/mNq3zwq/eval.jpg", "url":"https://medium.com/@ariful4966/ten-things-help-for-developer-af95d23d77a6", "website":"medium.com"},
    {"key":"BLOG07", "name":"As a developer, you need to have an idea about these things","about":"Variable declarations using var are treated as if they are at the top of the function regardless of where the actual declaration occurs", "img":"https://i.ibb.co/QvRXZBK/js-hoisting.jpg", "url":"https://medium.com/@ariful4966/as-a-developer-you-need-to-have-an-idea-about-these-things-deec8c71b4d9", "website":"medium.com"},
    {"key":"BLOG08", "name":"About some knowledge to JavaScript","about":"JavaScript is the most popular language in every web developer because there are many features useful to us.", "img":"https://i.ibb.co/RDQGTj4/es6.png", "url":"https://medium.com/@ariful4966/about-some-knowledge-to-javascript-8f991db64e97", "website":"medium.com"},
];
export default blogData;